In [ ]:
import numpy as np

data = np.array([
    [100, 0.001, 50],
    [200, 0.003, 60],
    [300, 0.002, 55],
    [400, 0.005, 65]
    
])

print("Original Data:\n", data)


Original Data:
 [[1.0e+02 1.0e-03 5.0e+01]
 [2.0e+02 3.0e-03 6.0e+01]
 [3.0e+02 2.0e-03 5.5e+01]
 [4.0e+02 5.0e-03 6.5e+01]]


In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaled_data=scaler.fit_transform(data)
print("\nMin-Max Scaled Data:\n", scaled_data)



Min-Max Scaled Data:
 [[0.         0.         0.        ]
 [0.33333333 0.5        0.66666667]
 [0.66666667 0.25       0.33333333]
 [1.         1.         1.        ]]


In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaled_data=scaler.fit_transform(data)
print("\nStandardized Data:\n", scaled_data)



Standardized Data:
 [[-1.34164079 -1.18321596 -1.34164079]
 [-0.4472136   0.16903085  0.4472136 ]
 [ 0.4472136  -0.50709255 -0.4472136 ]
 [ 1.34164079  1.52127766  1.34164079]]


In [6]:
import pandas as pd 

exampleData={
  'Name': ['Tom', 'nick', 'krish', 'jack'],
    'Age': [20, 21, 19, 18],
    'Salary': [20000, 25000, 18000, 15000],
}

df=pd.DataFrame(exampleData)
print(df)

    Name  Age  Salary
0    Tom   20   20000
1   nick   21   25000
2  krish   19   18000
3   jack   18   15000


In [11]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({
    'Name': ['Tom', 'Nick', 'John', 'Anna'],
    'Age': [25, 32, 47, 51],
    'Salary': [50000, 64000, 120000, 90000]
})

print("Original DataFrame:\n", df)

# Select only numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

scaler = MinMaxScaler()

# Fit_transform only numeric columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("\nDataFrame after Min-Max scaling numeric columns:\n", df)


Original DataFrame:
    Name  Age  Salary
0   Tom   25   50000
1  Nick   32   64000
2  John   47  120000
3  Anna   51   90000

DataFrame after Min-Max scaling numeric columns:
    Name       Age    Salary
0   Tom  0.000000  0.000000
1  Nick  0.269231  0.200000
2  John  0.846154  1.000000
3  Anna  1.000000  0.571429
